export const STRING_MAX_LENGTH = 11;
export const FIBONACCI_MAX_NUMBER = 19;
export const STACK_STRING_MAX_LENGTH = 4;
export const STACK_MAX_LENGTH = 19;
export const QUEUE_MAX_SIZE = 7;
export const QUEUE_STRING_MAX_LENGTH = 4;
export const LIST_STRING_MAX_LENGTH = 4;
export const LIST_INIT_VALUES = ['0', '34', '8', '1'];
export const LIST_MAX_LENGTH_ARR = 13;